/*
 * @Author: huazihear 
 * @Date: 2019-05-22 21:19:00 
 * @Last Modified by: huazihear
 * @Last Modified time: 2019-06-19 20:41:52
 * 
 * 一个字符串操作工作集合
 * 字符串是从浏览器环境取的一些key的集合 window和document
 * 暴露出一些 ast相关的方法 方便插入垃圾代码
 * 
 */
import { StringLiteral, stringLiteral, ExpressionStatement, AssignmentExpression, assignmentExpression, identifier, expressionStatement, VariableDeclaration, variableDeclaration, variableDeclarator, isIdentifier} from '@babel/types';
import * as freeNumber from './freeNumber';
const constString = 'locationjQuery111105648179404066014implementationURLdocumentURIcompatModecharacterSetcharsetinputEncodingcontentTypedoctypedocumentElementxmlEncodingxmlVersionxmlStandalonedomainreferrercookielastModifiedreadyStatetitledirbodyheadimagesembedspluginslinksformsscriptscurrentScriptdefaultViewdesignModeonreadystatechangeanchorsappletsfgColorlinkColorvlinkColoralinkColorbgColorallscrollingElementonpointerlockchangeonpointerlockerrorhiddenvisibilityStatewebkitVisibilityStatewebkitHiddenonbeforecopyonbeforecutonbeforepasteonsearchonvisibilitychangefontsoncopyoncutonpasteactiveElementstyleSheetspointerLockElementfullscreenElementadoptedStyleSheetsonabortonbluroncanceloncanplayoncanplaythroughonchangeonclickoncloseoncontextmenuoncuechangeondblclickondragondragendondragenterondragleaveondragoverondragstartondropondurationchangeonemptiedonendedonerroronfocusoninputoninvalidonkeydownonkeypressonkeyuponloadonloadeddataonloadedmetadataonloadstartonmousedownonmouseenteronmouseleaveonmousemoveonmouseoutonmouseoveronmouseuponmousewheelonpauseonplayonplayingonprogressonratechangeonresetonresizeonscrollonseekedonseekingonselectonstalledonsubmitonsuspendontimeupdateontoggleonvolumechangeonwaitingonwheelonauxclickongotpointercaptureonlostpointercaptureonpointerdownonpointermoveonpointeruponpointercancelonpointeroveronpointeroutonpointerenteronpointerleaveonselectstartonselectionchangechildrenfirstElementChildlastElementChildchildElementCountfullscreenEnabledfullscreenonfullscreenchangeonfullscreenerrorwebkitIsFullScreenwebkitCurrentFullScreenElementwebkitFullscreenEnabledwebkitFullscreenElementonwebkitfullscreenchangeonwebkitfullscreenerrorrootElementgetElementsByTagNamegetElementsByTagNameNSgetElementsByClassNamecreateDocumentFragmentcreateTextNodecreateCDATASectioncreateCommentcreateProcessingInstructionimportNodeadoptNodecreateAttributecreateAttributeNScreateEventcreateRangecreateNodeIteratorcreateTreeWalkergetElementsByNameopenclosewritewritelnhasFocusexecCommandqueryCommandEnabledqueryCommandIndetermqueryCommandStatequeryCommandSupportedqueryCommandValueclearcaptureEventsreleaseEventsexitPointerLockcreateElementcreateElementNScaretRangeFromPointgetSelectionelementFromPointelementsFromPointgetElementByIdprependappendquerySelectorquerySelectorAllexitFullscreenwebkitCancelFullScreenwebkitExitFullscreencreateExpressioncreateNSResolverevaluateregisterElementfeaturePolicywasDiscardedonfreezeonresumepictureInPictureElementpictureInPictureEnabledexitPictureInPictureELEMENT_NODEATTRIBUTE_NODETEXT_NODECDATA_SECTION_NODEENTITY_REFERENCE_NODEENTITY_NODEPROCESSING_INSTRUCTION_NODECOMMENT_NODEDOCUMENT_NODEDOCUMENT_TYPE_NODEDOCUMENT_FRAGMENT_NODENOTATION_NODEDOCUMENT_POSITION_DISCONNECTEDDOCUMENT_POSITION_PRECEDINGDOCUMENT_POSITION_FOLLOWINGDOCUMENT_POSITION_CONTAINSDOCUMENT_POSITION_CONTAINED_BYDOCUMENT_POSITION_IMPLEMENTATION_SPECIFICnodeTypenodeNamebaseURIisConnectedownerDocumentparentNodeparentElementchildNodesfirstChildlastChildpreviousSiblingnextSiblingnodeValuetextContenthasChildNodesgetRootNodenormalizecloneNodeisEqualNodeisSameNodecompareDocumentPositioncontainslookupPrefixlookupNamespaceURIisDefaultNamespaceinsertBeforeappendChildreplaceChildremoveChildaddEventListenerremoveEventListenerdispatchEvent'
+'undefiendgetElementByIdgetElementByTagNamepostMessageblurfocuscloseparentopenertoplengthframesclosedlocationselfwindowdocumentcustomElementshistorylocationbarmenubarpersonalbarscrollbarsstatusbartoolbarstatusframeElementnavigatororiginexternalscreeninnerWidthinnerHeightscrollXpageXOffsetscrollYpageYOffsetvisualViewportscreenXscreenYouterWidthouterHeightdevicePixelRatioclientInformationscreenLeftscreenTopdefaultStatusdefaultstatusstyleMediaonanimationendonanimationiterationonanimationstartonsearchontransitionendonwebkitanimationendonwebkitanimationiterationonwebkitanimationstartonwebkittransitionendisSecureContextonabortonbluroncanceloncanplayoncanplaythroughonchangeonclickoncloseoncontextmenuoncuechangeondblclickondragondragendondragenterondragleaveondragoverondragstartondropondurationchangeonemptiedonendedonerroronfocusoninputoninvalidonkeydownonkeypressonkeyuponloadonloadeddataonloadedmetadataonloadstartonmousedownonmouseenteronmouseleaveonmousemoveonmouseoutonmouseoveronmouseuponmousewheelonpauseonplayonplayingonprogressonratechangeonresetonresizeonscrollonseekedonseekingonselectonstalledonsubmitonsuspendontimeupdateontoggleonvolumechangeonwaitingonwheelonauxclickongotpointercaptureonlostpointercaptureonpointerdownonpointermoveonpointeruponpointercancelonpointeroveronpointeroutonpointerenteronpointerleaveonselectstartonselectionchangeonafterprintonbeforeprintonbeforeunloadonhashchangeonlanguagechangeonmessageonmessageerroronofflineononlineonpagehideonpageshowonpopstateonrejectionhandledonstorageonunhandledrejectiononunloadperformancestopopenalertconfirmpromptprintqueueMicrotaskrequestAnimationFramecancelAnimationFramecaptureEventsreleaseEventsrequestIdleCallbackcancelIdleCallbackgetComputedStylematchMediamoveTomoveByresizeToresizeByscrollscrollToscrollBygetSelectionfindwebkitRequestAnimationFramewebkitCancelAnimationFramefetchbtoaatobsetTimeoutclearTimeoutsetIntervalclearIntervalcreateImageBitmaponappinstalledonbeforeinstallpromptcryptoondevicemotionondeviceorientationondeviceorientationabsoluteindexedDBwebkitStorageInfosessionStoragelocalStoragechromespeechSynthesiswebkitRequestFileSystemwebkitResolveLocalFileSystemURLopenDatabaseapplicationCachecaches';

function getSomeString() : string {
    let max = freeNumber.randomFrom(2, constString.length);
    let min = max - (Math.floor(Math.random() * 10)) - 1;  
    min = min < 0 ? 0:min;
    return constString.substring(min,max);  
}

function getStringLiteral () : StringLiteral {
    return stringLiteral(getSomeString());
}

function getExpressionStatement(id: any, operator: string): ExpressionStatement {
    return expressionStatement(getAssignmentExpression(id, operator));
}

function getAssignmentExpression(id: any, operator: string): AssignmentExpression {
    if (!isIdentifier(id)) {
        id = identifier(id);
    }
    return assignmentExpression(operator, id, getStringLiteral());
}

function getVariableDeclaration(id: string): VariableDeclaration {
    return variableDeclaration('var', [variableDeclarator(identifier(id), getStringLiteral())])
}


//for循环索引变量名
let nameCode = 97;
let nameEndCode = 122;
let upNameCode = 90;
let upNameEndCode = 65;
function getName(): string {
    if (nameCode > nameEndCode){
        upNameCode--;
        nameCode = 97;
    }
    if (upNameCode > upNameEndCode) {
        upNameCode = 90;
    }

    return '_' 
        + freeNumber.getExceeParamNumber(0)
        + String.fromCharCode(nameCode++); 
}


function getVarName(num: number) {
    return '_' + Math.floor(Math.random() * num) + '_';
}


export {
    constString, //一个字符串常量
    getSomeString, // 返回一段字符串
    getStringLiteral,
    getExpressionStatement,
    getVariableDeclaration,
    getName,
    getVarName 
}